# docker-compose.yml
version: '3'

services:
  neo4j:
    image: neo4j:5.12.0
    container_name: business_consulting_kg
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      - NEO4J_AUTH=neo4j/password  # Change in production
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4JLABS_PLUGINS=["apoc", "graph-data-science"]
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/import:/import
      - ./neo4j/plugins:/plugins
    restart: unless-stopped

  postgres:
    image: postgres:15
    container_name: business_consulting_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password  # Change in production
      - POSTGRES_USER=app
      - POSTGRES_DB=business_consulting
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: unless-stopped